(() => {
const source=window.PORTFOLIO_PROJECTS||[], en=window.PORTFOLIO_EN||{};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const categoryIds={Conception:'design','Qualité':'quality','Systèmes':'systems',Maintenance:'maintenance'};
let lang=localStorage.getItem('portfolio-language')==='en'?'en':'fr', opener, activeFilter='all';
const staticEn=window.PORTFOLIO_STATIC_EN||{}, staticFr={};
Object.keys(staticEn).forEach(selector=>{const el=$(selector);if(el)staticFr[selector]=selector==='title'?document.title:el.getAttribute?.('content')??el.innerHTML});
const lists={fr:{nav:['Accueil','Projets','Parcours','Profil','Contact'],filters:['Tous','Conception','Qualité','Systèmes','Maintenance'],disciplines:['CONCEPTION MÉCANIQUE','QUALITÉ INDUSTRIELLE','MÉTROLOGIE','MÉTHODES & MAINTENANCE'],aria:{nav:'Navigation principale',filter:'Filtrer les projets',close:'Fermer la fiche projet',scene:'Sculpture mécanique interactive en 3D, anneaux noirs et dorés'}},en:{nav:['Home','Projects','Journey','Profile','Contact'],filters:['All','Design','Quality','Systems','Maintenance'],disciplines:['MECHANICAL DESIGN','INDUSTRIAL QUALITY','METROLOGY','METHODS & MAINTENANCE'],aria:{nav:'Main navigation',filter:'Filter projects',close:'Close project details',scene:'Interactive 3D mechanical sculpture with black and gold rings'}}};
function project(p){return lang==='en'?{...p,...en[p.id],gallery:p.gallery.map((g,i)=>[g[0],en[p.id]?.gallery?.[i]||g[1]])}:p}
function art(type){const strokes='fill="none" stroke="#d8b777" stroke-width="1.4"',svg={edf:'<path d="M55 170V80h190v90ZM70 95h70v60H70Zm100 0h55v60h-55ZM70 170v15m160-15v15M40 185h220M85 112h40m-40 12h40m-40 12h40"/><circle cx="197" cy="125" r="17"/><path d="m197 112 0 13 10 6M95 65h50v15m10-15h40v15"/>',meteo:'<rect x="80" y="55" width="140" height="140" rx="8"/><rect x="102" y="75" width="96" height="62" rx="4"/><path d="M95 155h20v20H95Zm40 0h25v20h-25Zm45 0h25v20h-25ZM80 85H55m25 30H55m25 30H55m165-60h25m-25 30h25m-25 30h25M112 105q12-17 25 0m10 0q12-17 25 0"/><circle cx="124" cy="116" r="3"/><circle cx="160" cy="116" r="3"/>',trotcargo:'<circle cx="75" cy="176" r="28"/><circle cx="238" cy="176" r="28"/><path d="M75 176h100l42-110h27M166 176h72L215 88M90 155l20-40h57v40ZM116 115V94h49v21M55 210h210"/>',palan:'<path d="M45 62h210v24H45Zm15 24v25h180V86M85 86v40m130-40v40M85 126h130v24H85Z"/><circle cx="103" cy="138" r="20"/><circle cx="197" cy="138" r="20"/><path d="M150 151v38q27 0 20 20t-38 0"/>',acmc:'<path d="m80 180 0-110 82-32 58 62v96l-70 25Zm0-110 70 40 70-10M150 110v111M100 83l43-18 22 23-40 16Z"/><path d="m90 170 45 24m32-1 39-14M63 70v120m-5-120h10m-10 120h10"/>'};return `<div class="graphic-cover ${type}"><svg viewBox="0 0 300 260" aria-hidden="true"><g fill="none" stroke="#ffffff09"><path d="M20 40h260M20 80h260M20 120h260M20 160h260M20 200h260M60 20v220M100 20v220M140 20v220M180 20v220M220 20v220M260 20v220"/></g><g ${strokes}>${svg[type]||svg.acmc}</g></svg><span class="graphic-label">${lang==='en'?'STUDY':'ÉTUDE'} / ${type.toUpperCase()} · ILLUSTRATION</span></div>`}
function renderProjects(){const projects=source.map(project);$('#total').textContent=projects.length;$('#project-grid').innerHTML=projects.map((p,i)=>`<article class="project-card" data-category="${categoryIds[source[i].category]}"><button data-project="${p.id}" aria-label="${lang==='en'?'View project':'Voir le projet'} : ${escape(p.short)}"><div class="project-media ${p.contain?'contain':''}">${p.image?`<img src="assets/${p.image}?v=20260920-3" alt="${escape(p.short)}" loading="lazy" width="800" height="550">`:art(p.graphic)}<span class="project-number">${String(i+1).padStart(2,'0')}</span><span class="project-arrow" aria-hidden="true">↗</span></div><div class="project-meta"><span>${p.category}</span><span>${p.context}</span></div><h3>${p.title}</h3><p>${p.summary}</p></button></article>`).join('');$$('[data-project]').forEach(b=>b.addEventListener('click',()=>openProject(b.dataset.project,b)));filter(activeFilter,false)}
function filter(value,announce=true){activeFilter=value;$$('[data-filter]').forEach(x=>{const on=x.dataset.filter===value;x.classList.toggle('selected',on);x.setAttribute('aria-pressed',on)});let n=0;$$('.project-card').forEach(c=>{c.hidden=value!=='all'&&c.dataset.category!==value;if(!c.hidden)n++});if(announce)$('#results').textContent=lang==='en'?`${n} project${n===1?'':'s'} shown`:`${n} projet${n>1?'s':''} affiché${n>1?'s':''}`}
function openProject(id,button){const p=project(source.find(x=>x.id===id));opener=button;$('#dialog-content').innerHTML=`<p class="dialog-kicker">${p.category.toUpperCase()} / ${p.context.toUpperCase()}</p><h2 id="dialog-title">${p.short}</h2><p class="intro">${p.intro}</p><div class="chips">${p.tools.map(t=>`<span>${t}</span>`).join('')}</div><div class="dialog-columns"><div><h3>${lang==='en'?'Approach':'Démarche'}</h3><ul>${p.work.map(a=>`<li>${a}</li>`).join('')}</ul></div><div><h3>${lang==='en'?'What this project shows':'Ce que présente le projet'}</h3><p>${p.result}</p></div></div>${p.gallery.length?`<div class="gallery">${p.gallery.map(([src,caption])=>`<figure><img src="assets/${src}?v=20260920-3" alt="${caption}" loading="lazy"><figcaption>${caption}</figcaption></figure>`).join('')}</div>`:''}<p class="source-note">Source : ${p.source}</p>`;$('#project-dialog').showModal();document.body.classList.add('modal-open');$('#project-dialog').scrollTop=0}
function applyLanguage(next){lang=next;localStorage.setItem('portfolio-language',lang);document.documentElement.lang=lang;const copy=lang==='en'?staticEn:staticFr;Object.entries(copy).forEach(([selector,value])=>{const el=$(selector);if(!el)return;if(selector==='title')document.title=value;else if(selector.startsWith('meta'))el.setAttribute('content',value);else el.innerHTML=value});const l=lists[lang];$$('.dock a span').forEach((el,i)=>el.textContent=l.nav[i]);$$('[data-filter]').forEach((el,i)=>{el.innerHTML=l.filters[i]+(i===0?' <span id="total"></span>':'')});$$('.discipline-bar span').forEach((el,i)=>el.textContent=l.disciplines[i]);$('.dock').setAttribute('aria-label',l.aria.nav);$('.filterbar').setAttribute('aria-label',l.aria.filter);$('.close-dialog').setAttribute('aria-label',l.aria.close);$('#scene').setAttribute('aria-label',l.aria.scene);$('.discipline-bar').setAttribute('aria-label',lang==='en'?'Areas of expertise':'Domaines de compétences');$('.wordmark').setAttribute('aria-label',lang==='en'?'Warren Comuce, home':'Warren Comuce, accueil');$('.portrait img').alt=lang==='en'?'Portrait of Warren Comuce':'Portrait de Warren Comuce';$('.current img').alt=lang==='en'?'BOUMA logo':'Logo BOUMA';const language=$('#language');language.querySelector('.language-current').textContent=lang.toUpperCase();language.querySelector('.language-next').textContent=lang==='fr'?'EN':'FR';language.setAttribute('aria-label',lang==='fr'?'Afficher le portfolio en anglais':'Display the portfolio in French');$$('.dock a').forEach((a,i)=>a.setAttribute('aria-label',l.nav[i]));setMenu(menuToggle.getAttribute('aria-expanded')==='true');$('#explode').innerHTML=$('#explode').getAttribute('aria-pressed')==='true'?(lang==='en'?'Reassemble <span>↙</span>':'Réassembler <span>↙</span>'):(lang==='en'?'Exploded view <span>↗</span>':'Vue éclatée <span>↗</span>');setMotion(window.portfolioMotion);renderProjects()}
$$('[data-filter]').forEach(b=>b.addEventListener('click',()=>filter(b.dataset.filter)));$('#language').addEventListener('click',()=>applyLanguage(lang==='fr'?'en':'fr'));
const menuToggle=$('#menu-toggle'),dock=$('.dock');function setMenu(open){dock.classList.toggle('open',open);menuToggle.classList.toggle('open',open);menuToggle.setAttribute('aria-expanded',open);menuToggle.setAttribute('aria-label',lang==='en'?(open?'Close menu':'Open menu'):(open?'Fermer le menu':'Ouvrir le menu'))}menuToggle.addEventListener('click',()=>setMenu(menuToggle.getAttribute('aria-expanded')!=='true'));$$('.dock a').forEach(a=>a.addEventListener('click',()=>setMenu(false)));document.addEventListener('pointerdown',e=>{if(menuToggle.getAttribute('aria-expanded')==='true'&&!dock.contains(e.target)&&!menuToggle.contains(e.target))setMenu(false)});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&menuToggle.getAttribute('aria-expanded')==='true'){setMenu(false);menuToggle.focus()}});addEventListener('resize',()=>{if(innerWidth>700)setMenu(false)});
const dialog=$('#project-dialog');$('.close-dialog').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{const r=dialog.getBoundingClientRect();if(e.target===dialog&&(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom))dialog.close()});dialog.addEventListener('close',()=>{document.body.classList.remove('modal-open');opener?.focus()});
$('#copy-email').addEventListener('click',async()=>{try{await navigator.clipboard.writeText('warren.comuce@gmail.com');$('#copy-status').textContent=lang==='en'?'Address copied.':'Adresse copiée.'}catch{$('#copy-status').textContent=(lang==='en'?'Address to copy: ':'Adresse à copier : ')+'warren.comuce@gmail.com'}});
const reduced=matchMedia('(prefers-reduced-motion: reduce)');window.portfolioMotion=!reduced.matches;function setMotion(on){window.portfolioMotion=on;document.body.classList.toggle('paused',!on);$('#motion').setAttribute('aria-pressed',!on);$('#motion').setAttribute('aria-label',on?(lang==='en'?'Pause animations':'Mettre les animations en pause'):(lang==='en'?'Play animations':'Activer les animations'));$('#motion').textContent=on?'Ⅱ':'▷';window.dispatchEvent(new Event('motionchange'))}setMotion(!reduced.matches);$('#motion').addEventListener('click',()=>setMotion(!window.portfolioMotion));reduced.addEventListener('change',e=>setMotion(!e.matches));
const navSections=$$('main section[id]');const updateNav=()=>{let id='accueil';navSections.forEach(s=>{if(s.getBoundingClientRect().top<innerHeight*.45)id=s.id});$$('.dock a').forEach(a=>{const active=a.hash==='#'+id;a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current')})};addEventListener('scroll',updateNav,{passive:true});
if('IntersectionObserver' in window&&!reduced.matches){const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.1});$$('.section-heading,.education,.skill-row,.about-copy').forEach(el=>{el.classList.add('reveal');observer.observe(el)})}
const canvas=$('#trail'),ctx=canvas.getContext('2d');let points=[],frame=0;const fine=matchMedia('(pointer:fine)');function resize(){canvas.width=innerWidth;canvas.height=innerHeight}resize();addEventListener('resize',resize);function drawTrail(){ctx.clearRect(0,0,canvas.width,canvas.height);const now=performance.now();points=points.filter(p=>now-p.t<360);if(window.portfolioMotion&&points.length>1){for(let i=1;i<points.length;i++){ctx.strokeStyle=`rgba(216,183,119,${(i/points.length)*.65})`;ctx.lineWidth=1.4;ctx.beginPath();ctx.moveTo(points[i-1].x,points[i-1].y);ctx.lineTo(points[i].x,points[i].y);ctx.stroke()}}if(points.length)frame=requestAnimationFrame(drawTrail);else frame=0}addEventListener('pointermove',e=>{if(!fine.matches||!window.portfolioMotion||e.pointerType!=='mouse')return;points.push({x:e.clientX,y:e.clientY,t:performance.now()});if(points.length>28)points.shift();if(!frame)frame=requestAnimationFrame(drawTrail)},{passive:true});
applyLanguage(lang);
})();
