window.PORTFOLIO_EN = {
presse:{title:'A press, from idea to mechanism.',short:'Manual press',category:'Design',context:'CNAM / Mécavenir',summary:'Collaborative design of a roller press for small production runs.',intro:'A design management project: starting from a small-run printing need and developing an adjustable manual roller press.',work:['Functional analysis of the need','Concept comparison and architecture selection','Force and torque sizing','3D design and manufacturing study'],result:'A documented design solution and 3D views of the press. The visuals show the designed model.',tools:['Mechanical design','Functional analysis','Sizing'],gallery:['3D model view','Design detail','Alternative mechanism view'],source:'Original portfolio by Warren Comuce, April 2026.'},
pige:{title:'Assemble. Adjust. Measure.',short:'Measuring gauge',category:'Quality',context:'Industrial experience',summary:'Assembly and adjustment of a dimensional inspection instrument.',intro:'Assembling a measuring gauge involves mechanical assembly, component adjustment and verification of the instrument’s operation.',work:['Component assembly','Mechanical adjustment','Calibration','Final inspection'],result:'An assembly documented with photographs of the components and completed instrument.',tools:['Assembly','Metrology','Dimensional inspection'],gallery:['Measuring assembly','Assembly detail','Components','Assembly'],source:'Original portfolio and photographs by Warren Comuce, April 2026.'},
edf:{title:'Plan maintenance ahead.',short:'Compressor maintenance',category:'Maintenance',context:'EDF SEI · 2026',summary:'Maintenance plans, spare parts and a three-year forecast schedule.',intro:'During my internship at the EDF SEI power plant in Saint-Barthélemy, from 20 July to 28 August 2026, my assignment focused on structuring maintenance for eight air compressors.',work:['Analysis of manufacturer documentation','Maintenance plans for each machine family','Identification and cataloguing of spare parts','Excel schedule based on operating hours'],result:'A three-year forecast schedule refocused on the operational need after discussion with my supervisor. Actual readings update the forecasts and shift future due dates.',tools:['Excel','Preventive maintenance','Technical documentation'],gallery:[],source:'EDF SEI internship report, Warren Comuce, July–August 2026. Schematic cover illustration.'},
waterfountain:{title:'Water, without contact.',short:'WaterFountain',category:'Systems',context:'CNAM / Mécavenir · S8',summary:'Study of an Arduino-controlled automatic fountain with infrared detection.',intro:'As technical lead in a three-person team, I helped design a fountain that dispenses water when it detects a container.',work:['Sensor–controller–actuator architecture','Selection of the TCRT5000 sensor, pump and MOSFET control','Power supply and integration study','Contribution to technical documentation'],result:'Theoretical validation and 3D-printed mechanical components. The report states that the complete prototype could not be assembled or tested within the timeframe because of supply delays.',tools:['Arduino UNO','Sensors','3D printing'],gallery:['Enclosure design views','Manufactured mechanical component'],source:'WaterFountain final report, Aymeric Bardeur, Warren Comuce and Ramatoulaye Sane, semester 8. Submission date not stated.'},
retour:{title:'From defect to final inspection.',short:'Customer return',category:'Quality',context:'Industrial experience',summary:'Diagnosis, correction and inspection of a customer-returned product.',intro:'Handling a customer return from defect identification through final verification and intervention traceability.',work:['Defect analysis','Repair and re-engraving','Final inspection','Product traceability'],result:'An intervention documented with before-and-after photographs and an inspection stage.',tools:['Non-conformities','Corrective actions','Traceability'],gallery:['Before intervention','After intervention','Product inspection'],source:'Original portfolio and photographs by Warren Comuce, April 2026.'},
kart:{title:'Rethinking a PVC kart.',short:'PVC kart',category:'Design',context:'BUT GMP · S6',summary:'Technology review and team-based kart design in SolidWorks.',intro:'For the semester 6 applied project, our team studied a kart made primarily from PVC. We began by researching solutions and then created a 3D model.',work:['Review of kart architectures','3D design in SolidWorks','Component definition','General assembly drawing'],result:'A design package containing the assembly model, bill of materials and general drawing. Operation of the vehicle is not established by the documents used here.',tools:['SolidWorks','CAD','Teamwork'],gallery:['Kart 3W general assembly drawing'],source:'Semester 6 project, team and project presentation, Warren Comuce, Djibril Sacko and João Delgado Costa; Kart 3W general drawing.'},
meteo:{title:'Giving sensors an interface.',short:'Connected weather station',category:'Systems',context:'Embedded project',summary:'ESP8266, temperature, pressure and a web control interface.',intro:'The station program connects an ESP8266 to a BMP280 sensor, an OLED display and a web interface. It also provides MQTT data exchange and RGB LED control.',work:['Temperature and pressure acquisition','OLED display','Web interface and data exchange','LED colour and brightness control'],result:'A program documenting the station’s software architecture and functions. No experimental measurements are presented here.',tools:['ESP8266','BMP280','OLED','MQTT'],gallery:[],source:'ProgStationMeteoW.ino and Warren Comuce’s original portfolio. Schematic illustration; no real measurements shown.'},
spiruline:{title:'Designing a production unit.',short:'Spirulina production',category:'Design',context:'BUT GMP · S5',summary:'Concept for a spirulina production unit integrated into a container.',intro:'The semester 5 project involved developing a protein production unit. Our team studied a spirulina-growing system inside a converted container.',work:['Need analysis and solution research','Layout of tanks and equipment','Lighting and power considerations','Study of crop parameter monitoring'],result:'A production-unit concept presented in the project deck. This is a design study; no production yield was validated.',tools:['System design','Layout','Need analysis'],gallery:['Studied container layout'],source:'Semester 5 protein production project, Margaron, Lebon, Comuce and Sacko.'},
trotcargo:{title:'Exploring cargo mobility.',short:'TrotCargo',category:'Design',context:'BUT GMP · S4',summary:'Technology review covering chassis, folding systems and suspension.',intro:'A team research project around TrotCargo, addressing the mechanical functions of a cargo mobility vehicle.',work:['Chassis solution research','Folding and locking concepts','Suspension solution comparison','Wheel and braking system research'],result:'A technology review presenting possible technical solutions. The reference products studied are not personal creations.',tools:['Technology review','Mobility','Solution analysis'],gallery:[],source:'TrotCargo technology review, Warren Comuce, Matéu Bartoli, Ouassim Ben Haj Chaib and Djibril Sacko, semester 4. Original schematic cover.'},
robot:{title:'Programming movement.',short:'Introduction to robotics',category:'Systems',context:'BUT GMP · S5',summary:'PolyScope introduction and study of robotic handling sequences.',intro:'An introduction to robot programming: frames, waypoints, trajectories and input/output logic.',work:['PolyScope interface introduction','Study of waypoints and motion types','Programming logic and inputs/outputs','Pick-and-place task study'],result:'A learning report illustrated with screenshots from the programming environment.',tools:['PolyScope','Robotics','Programming'],gallery:['Screenshot from the robotics report'],source:'IPI robotics report, Warren Comuce, semester 5.'},
palan:{title:'Sizing a mechanical joint.',short:'Hoist trolley',category:'Design',context:'BUT GMP · S3',summary:'Study of bushings and a pinned mechanical connection.',intro:'A hoist-trolley design exercise with calculations focused on guide components and a joint between a toothed shaft and chain wheel.',work:['Load distribution across bushings','Speed and pressure–velocity factor study','Pinned-joint concept selection','Calculation note writing'],result:'An educational sizing study. The original calculations are not presented as validated values in this portfolio.',tools:['Sizing','Mechanics','Joints'],gallery:[],source:'Hoist trolley exercise, calculation note, Warren Comuce, semester 3. Original schematic cover.'},
acmc:{title:'Designing for the workshop.',short:'Sheet-metal design',category:'Design',context:'ACMC · 2023',summary:'Part modelling and technical documentation for manufacturing.',intro:'During my internship at Atelier de Chaudronnerie et de Mécanique de Conflans, from March to May 2023, I worked on mechanical design shaped by manufacturing constraints.',work:['3D sheet-metal modelling in SolidWorks','Technical drawing creation','Manufacturing file preparation','Workshop discussions on cutting, bending and assembly'],result:'A design experience grounded in workshop processes and described in my professional background.',tools:['SolidWorks','Sheet metal','Technical drawing'],gallery:[],source:'Warren Comuce 2026 résumé and original portfolio. Original schematic illustration; no customer parts reproduced.'}
};

window.PORTFOLIO_STATIC_EN = {
'title':'Warren Comuce | Design. Precision. Industry.','meta[name="description"]':'Warren Comuce, industrial engineering student. Projects in mechanical design, quality, metrology and maintenance. Joining BOUMA in Buc on 21 September 2026.',
'.skip':'Skip to content','.edition':'PORTFOLIO / INDUSTRIAL ENGINEERING','.top-contact':'Let’s talk <span>↗</span>',
'.hero .eyebrow':'<i></i> ENGINEERING STUDENT · CNAM / MÉCAVENIR','.hero .folio':'01 / EXPLORE','.hero-statement':'Ideas take shape.<br><em>Precision makes the difference.</em>','.hero-description':'From mechanical design to quality inspection,<br class="desktop"> I build my path close to the shop floor.','.hero-copy .button':'Explore my work <span>↘</span>',
'.scene-caption':'FORM STUDY / 001<br><small>MECHANICAL SCULPTURE</small>','.scene-hint':'Drag to rotate · Arrow keys','.status span:nth-child(2)':'NEW CHAPTER<strong>BOUMA · Buc <small>From 21.09.2026</small></strong>','.scroll-link':'SCROLL TO DISCOVER <span>↓</span>',
'.projects .section-heading .eyebrow':'01 / WORK','.projects .section-heading h2':'From concept<br>to <em>reality.</em>','.projects .section-heading>p':'From academic projects to industry experience.<br>A selection from my work since the BUT GMP.',
'.journey .section-heading .eyebrow':'02 / JOURNEY','.journey .section-heading h2':'Learn.<br><em>Put it into practice.</em>','.journey .section-heading>p':'Education to understand.<br>Industry to test ideas against reality.',
'.journey-grid>div:first-child .column-heading':'Experience <span>↗</span>','.journey-grid>div:last-child .column-heading':'Education <span>↗</span>',
'.current .tag':'NEW APPRENTICESHIP','.current .meta':'Buc · From 21 September 2026','.current div>p:not(.meta)':'A new step in my work-study engineering path.','.current .text-link':'Discover the company ↗',
'.timeline:nth-of-type(2) .meta':'20 JULY – 28 AUGUST 2026','.timeline:nth-of-type(2) .role':'Internship · Industrial methods & maintenance','.timeline:nth-of-type(2) div>p:last-child':'Compressor maintenance plans, spare parts and a forecast schedule in Excel.',
'.timeline:nth-of-type(3) .meta':'PREVIOUS EXPERIENCE','.timeline:nth-of-type(3) .role':'Apprenticeship · Quality controller','.timeline:nth-of-type(3) div>p:last-child':'Dimensional and geometric inspection, CMM, quality documentation and non-conformity analysis.',
'.timeline:nth-of-type(4) .meta':'MARCH – MAY 2023','.timeline:nth-of-type(4) .role':'Internship · Mechanical design','.timeline:nth-of-type(4) div>p:last-child':'SolidWorks sheet-metal design, technical drawings and manufacturing files in collaboration with the workshop.',
'.education:first-of-type .meta':'2024 – 2027 · IN PROGRESS','.education:first-of-type h4':'Industrial engineering<br>degree','.education:first-of-type>p:not(.meta)':'CNAM / Mécavenir · Mantes-la-Ville','.education:first-of-type .chips':'<span>Design</span><span>Production</span><span>Project management</span>',
'.education:last-of-type .meta':'2021 – 2024','.education:last-of-type h4':'Bachelor of Technology<br>Mechanical & Manufacturing Engineering','.education:last-of-type>p:not(.meta)':'IUT Saint-Denis · Sorbonne Paris Nord University','.education:last-of-type .chips':'<span>Mechanics</span><span>Manufacturing</span><span>Metrology</span>',
'.about-copy .eyebrow':'03 / BEHIND THE WORK','.about-copy h2':'Understand the part.<br><em>Think about the whole.</em>','.about-copy>p:nth-of-type(2)':'My background connects design, manufacturing and quality. I like to understand how a part is conceived, how it is made and how its conformity is verified.','.about-copy>p:nth-of-type(3)':'After a BUT GMP, I am pursuing an industrial engineering degree at CNAM with Mécavenir. My experience in workshops, quality inspection and maintenance gives this education a practical foundation.','.about-copy>p:nth-of-type(4)':'My goal is to grow into a quality or design engineering role while staying connected to the shop floor.','.about-copy .text-link':'Find me on LinkedIn ↗',
'.skills>.eyebrow':'04 / EXPERTISE','.skill-row:nth-of-type(1) h3':'Mechanical design','.skill-row:nth-of-type(1) p':'SolidWorks · Fusion 360 · CATIA · 3DExperience<br><small>Parts, assemblies, sheet metal and technical drawings.</small>','.skill-row:nth-of-type(2) h3':'Quality & metrology','.skill-row:nth-of-type(2) p':'CMM · MCOSMOS · Conventional instruments<br><small>Dimensional inspection, conformity and traceability.</small>','.skill-row:nth-of-type(3) h3':'Methods & maintenance','.skill-row:nth-of-type(3) p':'Maintenance plans · Spare parts · Excel<br><small>Documentation and intervention planning.</small>','.skill-row:nth-of-type(4) h3':'Systems & simulation','.skill-row:nth-of-type(4) p':'ESP8266 · Arduino · MATLAB / Simulink<br><small>Sensors, embedded programming and simulation.</small>',
'.contact>.eyebrow':'05 / CONTACT','.contact h2':'An idea.<br>A conversation.<br><em>A starting point.</em>','.contact-bottom p':'Let’s talk design, industry<br>or your next project.','.contact-bottom .button':'Write to me <span>↗</span>','#copy-email':'Copy address','footer span:nth-child(2)':'DESIGNED WITH PRECISION.','footer a':'Back to top ↑'
};
